name: Deploy to Azure with azd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install azd
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash

      - name: Log in with Azure (Federated Credentials)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        env:
          AZURE_LOCATION: "eastus"
          AZD_ENV_NAME: "chat-app"  # Add this line to set the environment name
        run: |
          azd auth login
          azd up --environment $AZD_ENV_NAME --location $AZURE_LOCATION
